= Free Software and the Public Administration
:experimental:
:icons: font
:page-partial:
:source-highlighter: highlightjs

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

include::{partialsdir}/README.adoc[tag=metadata]

== In practice

There are many examples of free software being used and created by public administrations both in Europe and across the world.
Munich's migration of its servers and desktops is a very well-known
casefootnote:[_Presentation on the Declaration of Independence: The LiMux Project in Munich, available online at https://joinup.ec.europa.eu/sites/default/files/fe/cb/fa/IDABC.OSOR.casestudy.LiMux.pdf_],
but there is a long list of other examples, such as the migration of Linux servers and desktops at Zaragoza City
Councilfootnote:[_Free software desktop migration, available online at https://www.zaragoza.es/contenidos/azlinux/migracionescritoriosl.pdf. Further information at https://www.zaragoza.es/ciudad/sectores/tecnologia/swlibre/zo2.htm_].

In its _Interoperable Delivery of European eGovernment Services to Public Administrations, Businesses and Citizens_ initiative (now known as JoinUp), the European Commission established an “Open Source Observatory” (OSOR) that collects information about benchmark cases on the adoption of free software in the EUfootnote:[_Open source observatory, available online at https://joinup.ec.europa.eu/node/26689_]: it reveals that literally thousands of cities and regions have installed and run free software across Europe.
JoinUp asserts that more than 15,000 projects are licensed under the EUPL free software licence (see below), the majority pertaining to European administrations.footnote:[_More projects licensed under EUPL (15,000 according to GitHub), available online at https://joinup.ec.europa.eu/community/eupl/news/more-projects-licensed-under-eupl-15000-according-github_] JoinUp has also established a European federation of free software repositoriesfootnote:[_JoinUp: About federated repositories, available online at https://joinup.ec.europa.eu/catalogue/repository_], making it possible to search for and identify existing freely licenced solutions.

****
[quote, European Comission, https://ec.europa.eu/info/european-commissions-open-source-strategy_en]
____
The European Commission will further increase the role of open source software for many of its key ICT services and software solutions. The renewed strategy puts a special emphasis on procurement, contribution to open source software projects and providing more open source software in the Commission.
____
****

The European Commission's free software strategy policy was published in 2014, reinforcing its desire to release free software created by or on behalf of the Commission, in addition to contributing to and participating in development communities.footnote:[_EC Open Source Software Strategy, available online at https://ec.europa.eu/info/european-commissions-open-source-strategy_en_]

In Spain, the most notable example of software being released and used is the LinEx project in Extremadura, in addition to the Andalusian code repository (endorsed by Order of 21 February 2005, on the public availability of the IT programs of the Regional Government of Andalusia and its autonomous organisms).
Since then, various versions of Linux have been created by the Spanish administrations (including Linkat, for the Catalan educational communityfootnote:[Online at http://linkat.xtec.cat/portal/index.php[http://linkat.xtec.cat/portal/index.php]]).
The central Government also maintains a repository of reusable software (at the Technology Transfer Centrefootnote:[Online at https://administracionelectronica.gob.es/pae_Home/pae_SolucionesCTT/pae_CTT_-__Que_es_.html and the Github account is at https://github.com/ctt-gob-es.] ) and its own GitHub account.

Barcelona City Council itself has released Sentilofootnote:[Sentilo Project, online at http://www.sentilo.io], a sensor data management platform, developed for the city, whilst the Catalan Regional Government has released a range of projects, including EinesTICfootnote:[Generalitat de Catalunya, EinesTIC, online at http://sac.gencat.cat/sacgencat/AppJava/servei_fitxa.jsp?codi=14232].

== Advantages

The advantages of the public administration using free software has been addressed countless times.
Without looking further, we would highlight the recommendations proposed to the Spanish Central State Administration on the use of free software, MAP, in June 2005.
In summary, this document outlines the following legal advantages:

[loweralpha]
. Obtaining sufficient software rights (control, on the one hand, and freedom, on the other) to optimise its management: updates, redistribution, etc.
. Benefiting from the freedom of internal and external copying and redistribution by the public administration.
. Contributing to the pooling and reuse of software amongst public administrations (IDA, national).
. Satisfying the legal framework for public action (effectiveness, efficiency, conversation, security, standardisation and interoperability, access and linguistic respect, reuse of resources).

These advantages have also been studied and presented by Cenatic, the Spanish National _Reference Centre for the Application of Open Source Information and Communication Technologies_ (belonging to Red.es at the Ministry of Energy, Tourism and Digital Agenda), for example, in its publication “_Diez razones para el uso de software de fuentes abiertas en la educación”_ (Ten reasons to use open source software in education) or “_Diez razones para que la administración libere software”_ (Ten reasons for the administration to release free software)footnote:[_Available online at_ _http://www.cenatic.es/index.php?option=com_content&view=article&id=25669_ and _http://www.cenatic.es/publicaciones/divulgativas?download=21%3A10-razones-para-que-la-administracion-libere-software-extendido respectively._] it includes the following amongst the list of advantages:

* Independence from the software's manufacturer: thanks to the free licence, public administrations and user companies can control the use of technology and enjoy more freedom in designing their future technology strategy.
* Cost savings: thanks to the sharing, reuse and absence of costs associated with free licences, there are significant savings in terms of the end price of applications, whilst using software that is 100% legal.
* Greater software security and quality: by publishing the source code, it makes it possible for the developer community to constantly contribute to the security and quality of the software, correcting any errors detected and thus helping the application evolve more quickly.
* Development of the local ICT sector: as they have access to the code, SMEs in the sector can offer services to public administrations and companies in such a way that they can compete under better conditions with other more dominant operators in the sector.
* Value generation in the community: using free software allows public administrations and companies to share and reuse applications, enhancing collaboration between these entities and with the technology industry and developer community.footnote:[_Available online at http://www.cenatic.es/sobre-el-software-libre/ventajas-del-software-libre_]

****
[quote, Basque Parliament, "Decree 159/2012, of 24 July, regulating the openness and reuse of IT platforms by the Public Administration in the Basque Country"]
____
The resulting reuse makes it possible to enhance cost savings as part of the development, maintenance and evolution of the source code. However, primarily, it promotes the development of an economy based on knowledge and innovation, and contributes to the development of an information and communication technology ecosystem, improving the competition by encouraging cooperation between the public and private sector with the sole objective of improving public services, the quality of which are usually based on the mass use of information technologies.
____
****

== Legal framework

It is clear that Spanish public administrations are competent in terms of acquiring and using free software, exchanging it among themselves and releasing the software they own to the community.
In Spain, a number of general provisions tend to favour the use of free software in the public administration.

[loweralpha]
. The most relevant was originally in Chapter III, Title IV of Law 11/2007, of 22 June, on electronic access of citizens to public services (LAECSP), entitled “Reuse of applications and technology transfer” (now *Art. 157 and 158 of Law 40/2015)*, which establishes measures that, without directly promoting free software, facilitate (a) the reuse of IT resources between administrations, (b) the *creation of software repositories* for subsequent reuse (such as the Technology Transfer Centre repository of the Spanish Central Government) and (c) the *release* of applications owned by public administrations under free licences.
. Furthermore, *the seventeenth additional provision of Law 57/2007*, of 28 December, establishing Measures to Promote the Information Society, states that public administrations may make *digital content* available to the public for which there are no restrictions on intellectual property rights, or for which said rights are in the public domain, subject to licences that facilitate the study, copy and redistribution under the same terms (i.e., with a degree of _copyleft_).
. More importantly, *Royal Decree 4/2010*, of 8 January, regulating the National System of Interoperability in the scope of e-Government provides as follows:

* Article 16 establishes the licensing conditions applicable to reusable IT applications declared as “open source”, and in particular applications that can be redistributed to other users on the condition that the derivative work retains the previous conditions, in other words, with a degree of _copyleft_ (weak or strong).
Furthermore, in terms of the release of software, Article 16 recommends the use of the EUPL licence, without prejudice to other licenses that guarantee the aforementioned rights.
* Article 17 defines specific conditions applicable both to repositories of software for free reuse (in terms of their association with equivalent instruments at other public administrations) and the duty to consider solutions available to public administrations that may fully or partially satisfy the needs of new systems or services, improvements or updates to those already rolled out, and conditions in terms of the publication of the source code of IT applications in the aforementioned directories in order to promote sharing, reuse and collaboration in the pursuit of increased effectiveness and efficiency.

At a regional level, for example, there is the *Order, of 21 February 2005*, on the public availability of the IT programmes of the Regional Government of Andalusia and its and its autonomous organisms, and more recently, *Decree 159/2012, of 24 July*, regulating the openness and reuse of IT platforms by the public administration in the Basque Country.footnote:[_Decree 159/2012, of 24 July, regulating the openness and reuse of IT platforms by the public administration in the Basque Country; and Order, of 25 September 2012, of the Department of the Interior, Justice and the Public Administration, approving the policy of openness and reuse of IT platforms by the public administration in the Basque Country._] Both promote the use and reuse of free software and the creation of repositories to facilitate the aforementioned actions.

The Italian Constitutional Courtfootnote:[_Italian Constitutional Court in 2010, Decision no. 122 of March 22._] has ruled that promoting free software based solutions does not distort competition nor is it against the public-sector procurement law (in Italy), since stipulating the legal conditions for supplying software (the free software licence) and does not amount to technological, trademark or provider discrimination, rather is a legal condition in the specifications that all suppliers must fulfil.

The various laws to which Barcelona City Council is subject does not exclude nor require the use of free software within the Administration; however, some of the criteria established for acquiring software, such as the promotion of reuse or the need for interoperability, are achieved more effectively, consistently and in a more lasting way with free software licencing.

== Public Procurement of Free Software

In terms of the conditions for acquiring technologies for the administrations’ digital services as free software or free software-based applications, although no European country makes it mandatory to use free software, most ban discrimination against providers that submit bids involving free software, based on the principles of free competition and non-discrimination.
However, they do require that supplied software complies with open and internationally recognised standards.

Other regulatory frameworks establish a preference for the use of free technologies.
In 2014, for example, the Italian government promoted free solutions, establishing an order of priority in terms of the analysis of proposals: administrations must give preference to free solutions over proprietary software and cloud solutions.

In Spain, software and software-related services supplied to the public administrations are primarily regulated by the Royal Legislative Decree 3/2011, of 14 November, approving the revised text of the public-sector procurement law (recently updated).
Beyond the standard public procurement procedures (specifications, bids, awards, enforcement and resolution, etc.), the following points are important in terms of free software:

* This law considers the provision of “base” or standard software (belonging to third parties) as a supply, whilst tailor-made individual developments are considered services (Art. 9 and 10)
* In the second case, the service provider (of the development) must transfer the rights of the modifications and customisations and other developments delivered under the contract to the public administration, unless established otherwise in the administrative specifications (Art. 301).

It is also worth noting that Article 17 of Royal Decree 4/2010, of 8 January, obliges administrations to consult the repositories and existing reusable solutions before procuring a new technology.

== Licences for freeing public administration software

Article 16 of the aforementioned Royal Decree 4/2010, of 8 January, establishes the conditions for Spanish public administrations to follow when releasing software.
Two of them are:

[quote, Cortes Generales (Spanish Parliament), "Royal Decree 4/2010, of 8 January"]
____
[start=2]
. In terms of the applications certified as open source, administrations shall use licences that guarantee that the programmes, data or information shared:
.. Can be executed for any purpose.
.. Allow for the source code to be consulted.
.. Can be modified or improved.
.. Can be redistributed to other users either with or without changes, provided that the derivative work preserves the same four guarantees.
. To this end, they shall procure the use of the European Union Public Licence, without prejudice to other licences that guarantee the same rights as those set out in sections 1 and 2.
____

This means that a public administration can use any current free software licence, provided that it contains an element of copyleft (condition 2(d) above) and it is “recommended” to use the EUPL licence.
For releasing software by the European Commission or the EU and, by extension, other public administrations, a study was carried out in 2005 and it was established that no existing free licence was ideal, even though many may serve the purpose.
Therefore, in 2007 (and updated in 2017), the _European Union Public Licence_ (EUPL) was published, which is a licence with weak _copyleft_.

****
The EUPL is a particularly interesting licence given its appendix on “compatible” or “interoperable licences”.
To avoid licence conflicts, the EUPL allows licensees to redistribute derivative works (and combinations or composites) under a compatible licence or under an incompatible licence indicated in the appendix (including the Eclipse PL, OSL 2.0 and 3.0, CeCILL, LGPLv2.1 and GPLv2 and now GPLv3 and AGPLv3).
This express compatibility and the interoperability policy is applied to the final result of any integration (and not the original components that retain their own licence).
Therefore, these terms of interoperability respect the original licence, whilst permitting interoperability with other, normally incompatible, copyleft licences.footnote:[See description of EUPL “The European Union Public Licence (EUPL)”, available online at https://www.ifosslr.org/ojs/ifosslr/article/view/91; and “Comments to Understanding the EUPL 1.2”, available online at https://joinup.ec.europa.eu/news/understanding-eupl-v12.]
****
