= Free software

== Concept and definitions


The general principles underpinning free software are ...


== CopyLeft


Free software licences with _copyleft_ go beyond ...


== Free software licences


Within the general framework of these freedoms, there are ...


== Advantages


The legal and practical impact of free software licences is ...




= Free Software and the Public Administration

== In practice


There are many examples of ...


== Advantages


The advantages of ...


== Legal framework


It is clear that Spanish public administrations are ...


== Public Procurement of Free Software


In terms of the conditions for ...


== Licences for freeing public administration software


Article 16 of the aforementioned Royal Decree 4/2010, of 8 January, establishes ...


= Interoperability, open standards and formats


Interoperability is the capacity of ...


= Policy on technological sovereignty and guidelines for its implementation

== Principles and guidelines


The policy on the technological sovereignty of the City Council is based on ...


== Open standards and interoperability


The digital services of Barcelona City Council must be implemented using ...


== Free software and the reuse of resources


The City Council's policy in terms of ...
